version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - n 20  # Force Node update to v16
      - echo -e '@neverendingsupport:registry=https://registry.nes.herodevs.com/npm/pkg/\n//registry.nes.herodevs.com/npm/pkg/:_authToken="'${NES_AUTH_TOKEN}'"' > .npmrc
      - npm -v
      - npm install

  build:
    commands:
      - npm run build-vue

  post_build:
    commands:
      - chmod 755 ./scripts/*.sh
      - ./scripts/create-build-summary.sh

artifacts:
  files:
  - '.ebextensions/**/*'
  - '.platform/**/*'
  - 'application.py'
  - 'config/**/*'
  - 'consoler.py'
  - 'dist/**/*'
  - 'fixtures/**/*'
  - 'nessie/**/*'
  - 'requirements.txt'
  - 'scripts/**/*'
