# Tox (https://tox.readthedocs.io/) is a tool for running tests in multiple virtualenvs.

[tox]
envlist =
    lint-py,
    lint-vue,
    build-vue,
    test
skipsdist = True

[testenv]
allowlist_externals = *

[testenv:lint-vue]
commands = npm run lint-vue {posargs}

[testenv:lint-vue-fix]
commands = npm run lint-vue-fix {posargs}

[testenv:build-vue]
commands = npm run build-vue

[testenv:test]
commands = pytest --durations=10 {posargs: -p no:warnings tests}

[testenv:lint-py]
commands = ruff check {posargs:application.py config consoler.py nessie scripts tests}
